# Generated by Django 5.0 on 2024-01-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Приз')),
                ('description', models.CharField(max_length=30, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.IntegerField(verbose_name='Размер')),
                ('Ammo', models.IntegerField(verbose_name='Выстрелы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(verbose_name='X')),
                ('Y', models.IntegerField(verbose_name='Y')),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grounds.flat')),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grounds.gifts')),
            ],
        ),
    ]
