# Generated by Django 5.0 on 2024-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='Ammo',
            field=models.IntegerField(default='2', verbose_name='Выстрелы'),
        ),
    ]
