# Generated by Django 5.0 on 2024-01-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0004_winnings_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winnings',
        ),
    ]
