# Generated by Django 5.0 on 2024-01-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
