# Generated by Django 5.0 on 2024-01-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rule', models.CharField(max_length=512, verbose_name='Правила')),
            ],
        ),
    ]
