# Generated by Django 5.0.1 on 2024-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='Rule',
            field=models.TextField(verbose_name='Правила'),
        ),
    ]
